config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "publishers#index"

  resources :publishers

  namespace :api do
    resources :blogs, only: [:index, :show, :create, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    super + ['_all']
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true

  mount_uploader :image, AvatarUploader

end

app/models/blog.rb
class Blog < ApplicationRecord

end

app/models/publisher.rb
class Publisher < ApplicationRecord

  belongs_to :user

  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :publishers
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  include RenderJson

  def meta
    @meta || {}
  end
end

app/controllers/api/blogs_controller.rb
class Api::BlogsController < Api::BaseController

  before_action :set_blog, only: [:show, :update, :destroy]

  def index
    q = {
      author_eq: params[:author],
      title_cont: params[:title],
      desc_cont: params[:desc]
    }
    @blogs = Blog.ransack(q).result.order("id desc").page(params[:page]).per(params[:per_page])
    @meta = meta.merge(
      total_page: @blogs.total_pages,
      total_count: @blogs.total_count,
      current_page: (params[:page] || 1)
    )
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      render_200({id: @blog.id})
    else
      render_400(@blog.errors.messages)
    end
  end

  def update
    if @blog.update(blog_params)
      render_200({id: @blog.id})
    else
      render_400(@blog.errors.messages)
    end
  end

  def show
    
  end

  def destroy
    if @blog.destroy
      render_200
    else
      render_400
    end
  end

  private
    def blog_params
      params.permit(
        :author, 
        :title, 
        :desc
      )
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  before_action :authenticate_user!

  before_action :set_publisher, only: [:edit, :update, :show, :destroy]

  def index
    @q = current_user.publishers.includes(:attachments).ransack(params[:q])
    @publishers = @q.result.order("id desc").page(params[:page]).per(10)
  end

  def new
    @publisher = Publisher.new
    @publisher.attachments.build
    @publisher.attachments.build
  end

  def create
    @publisher = current_user.publishers.new(publisher_params)
    if @publisher.save
      redirect_to publishers_path
    else
      render :new
    end  
  end

  def edit

  end

  def update
    if @publisher.update(publisher_params)
      redirect_to publisher_path(@publisher)
    else
      render :edit
    end
  end

  def show

  end

  def destroy
    if @publisher.destroy
      redirect_to publishers_path
    else
      redirect_to publisher_path(@publisher), alert: 'Failed to delete publisher'
    end
  end

  private
    def set_publisher
      @publisher = current_user.publishers.find(params[:id])
    end

    def publisher_params
      params.require(:publisher).permit(
        :name,
        :card_no,
        :birthday,
        attachments_attributes: [:id, :image]
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand d-flex w-50 me-auto" href="/">LOGO</a>
          <% if current_user %>
            <div>
              Welcome: <%= current_user.email %>
              <%= link_to "Sign out", destroy_user_session_path(authenticity_token: form_authenticity_token), data: { turbo: true, turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
            </div>
          <% else %>
            <div><%= link_to "Login", new_user_session_path %></div>
          <% end%>
        </div>
      </nav>
    </header>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <%= link_to "Publisher List", publishers_path, class: "list-group-item" %>
          </div>
        </div>
        <div class="col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/publishers/_form.html.erb
<%= form_for @publisher, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :card_no %>
  <%= f.text_field :card_no %>

  <%= f.label :birthday %>
  <%= f.text_field :birthday %>

  <label>Attachments:</label>
  <%= f.fields_for :attachments do |attachment| %>
    <%= image_tag attachment.object.image&.url if attachment.object.image&.url %>
    <%= attachment.file_field :image %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/publishers/edit.html.erb
<div>Edit Publisher</div>
<%= render 'form' %>

app/views/publishers/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= search_form_for @q do |f| %>
      <%= f.label :name_cont %>
      <%= f.search_field :name_cont %>

      <%= f.label :card_no_eq %>
      <%= f.search_field :card_no_eq %>

      <%= f.label :birthday_eq %>
      <%= f.search_field :birthday_eq %>

      <%= f.submit "Search" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= link_to "New Publisher", new_publisher_path %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= paginate @publishers %>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Card Number</th>
          <th>Birthday</th>
          <th>Image Count</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @publishers.each_with_index do |publisher, i| %>
          <tr>
            <td><%= i + 1 %></td>
            <td><%= publisher.name %></td>
            <td><%= publisher.card_no %></td>
            <td><%= publisher.birthday %></td>
            <td><%= publisher.attachments.size %></td>
            <td>
              <%= link_to "Detail", publisher_path(publisher) %>
              &nbsp;
              <%= link_to "Edit", edit_publisher_path(publisher) %>
              &nbsp;
              <%= link_to "Delete", publisher_path(publisher), data: {turbo: true, turbo_method: :delete, turbo_confirm: "Are you sure delete publisher?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @publishers %>
  </div>
</div>

app/views/publishers/new.html.erb
<div>Create Publisher</div>
<%= render 'form' %>

app/views/publishers/show.html.erb
<div class="row">
  <div class="col-sm-4">Name:<%= @publisher.name %></div>
  <div class="col-sm-4">Card Number: <%= @publisher.card_no %></div>
  <div class="col-sm-4">Birthday: <%= @publisher.birthday %></div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= link_to "Publisher List", publishers_path %>
  </div>
</div>